// @generated by protobuf-ts 2.9.3 with parameter server_grpc1,client_grpc1,optimize_code_size
// @generated from protobuf file "employees.proto" (syntax proto3)
// tslint:disable
import { EmployeeService } from "./employees";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { EmployeeResponse } from "./employees";
import type { EmployeeRequest } from "./employees";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service EmployeeService
 */
export interface IEmployeeServiceClient {
    /**
     * @generated from protobuf rpc: GetEmployee(EmployeeRequest) returns (EmployeeResponse);
     */
    getEmployee(input: EmployeeRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: EmployeeResponse) => void): grpc.ClientUnaryCall;
    getEmployee(input: EmployeeRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: EmployeeResponse) => void): grpc.ClientUnaryCall;
    getEmployee(input: EmployeeRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: EmployeeResponse) => void): grpc.ClientUnaryCall;
    getEmployee(input: EmployeeRequest, callback: (err: grpc.ServiceError | null, value?: EmployeeResponse) => void): grpc.ClientUnaryCall;
}
/**
 * @generated from protobuf service EmployeeService
 */
export class EmployeeServiceClient extends grpc.Client implements IEmployeeServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * @generated from protobuf rpc: GetEmployee(EmployeeRequest) returns (EmployeeResponse);
     */
    getEmployee(input: EmployeeRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: EmployeeResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: EmployeeResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: EmployeeResponse) => void)): grpc.ClientUnaryCall {
        const method = EmployeeService.methods[0];
        return this.makeUnaryRequest<EmployeeRequest, EmployeeResponse>(`/${EmployeeService.typeName}/${method.name}`, (value: EmployeeRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): EmployeeResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
